[package]
name = "sheets_web"
version = "0.1.0"
edition = "2024"

[dependencies]
sheets_core = { path = "../../core" }
actix-web.workspace = true
actix-multipart.workspace = true
uuid.workspace = true