repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        args: ["--manifest-path", "backend/Cargo.toml", "--all", "--", "--check"]
    -   id: clippy
        args: ["--manifest-path", "backend/Cargo.toml", "--workspace", "--all-targets", "--all-features", "--", "-D", "warnings"]
    -   id: cargo-check
        args: ["--manifest-path", "backend/Cargo.toml", "--workspace", "--all-features", "--all-targets"]
