services:
  db:
    image: postgres:17
    restart: no
    volumes:
      - db:/var/lib/postgresql/data
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: form-forge
    ports:
      - "5434:5432"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"

  adminer:
    image: adminer:5
    restart: no
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db: