[package]
name = "sheets_storage"
version = "0.1.0"
edition = "2024"

[dependencies]
sheets_core = { path = "../../core" }
actions_core = { path = "../../../actions/core" }
async-trait.workspace = true
anyhow.workspace = true
tracing.workspace = true
