[package]
name = "sheets_pdf"
version = "0.1.0"
edition = "2024"

[dependencies]
sheets_core = { path = "../../core" }
async-trait.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
uuid.workspace = true