[package]
name = "actions_pdf"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
actions_core = { path = "../../core" }
common = { path = "../../../common" }
async-trait.workspace = true
tracing.workspace = true
lopdf.workspace = true