[package]
name = "actions_pdf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actions_core = { path = "../../core" }
common = { path = "../../../common" }
async-trait.workspace = true
tracing.workspace = true
lopdf.workspace = true