[package]
name = "sheets_db"
version = "0.1.0"
edition = "2024"

[dependencies]
sheets_core = { path = "../../core" }
actions_core = { path = "../../../actions/core" }
async-trait.workspace = true
sqlx.workspace = true
tracing.workspace = true
