[package]
name = "actions_pdf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actions_core.workspace = true
common_pdf.workspace = true
async-trait.workspace = true
tracing.workspace = true
lopdf.workspace = true
